apiVersion: apps/v1
kind: Deployment
metadata:
  name: rescin-ticket-reservation-deployment
  namespace: rescin
spec:
  template:
    metadata:
      name: rescin-ticket-reservation
      labels:
        app: rescin-ticket-reservation
    spec:
      containers:
        - name: rescin-ticket-reservation
          image: rescin/ticket-reservation:{{ .Values.imageVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: QUARKUS_PROFILE
              value: {{ .Values.quarkusProfile }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: rescin-ticket-reservation

